I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 194, in script
    m "1v1 me REEEEEEEEEEEEE!"
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 194, in script
    m "1v1 me REEEEEEEEEEEEE!"
  File "D:\Program Files\Ren'py 6.99.12.4\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Program Files\Ren'py 6.99.12.4\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
The Bamboozle Dream Meme Team
